name: Brakeman Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 1 * * 5'

permissions:
  contents: read

jobs:
  brakeman-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Brakeman Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Setup Brakeman
      run: gem install brakeman --version 4.10

    - name: Scan
      continue-on-error: true
      run: brakeman -f sarif -o output.sarif.json .

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: output.sarif.json
